language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - coverage run `which nosetests`
notifications:
  email: false
  slack:
    - hasgeek:HDCoMDj3T4ICB59qFFVorCG8
    - friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
