language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - coverage run `which nosetests`
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
